### ISSUE TITLE
Macros require @ before them?

### ISSUE THREAD

**Issue by davecom** [c3lang/c3docs#21]
Trying to define a macro without @ like this one from the docs:
```c3
macro void swap(&a, &b) {
    $typeof(a) temp = a;
    a = b;
    b = temp;
}
```

I got this from the compiler:
Error: Names of non-function like macros (i.e. a macro with a trailing body, ref or expression parameters, must start with '@'

But the macro page has examples of macros with no @:
http://www.c3-lang.org/macros/

**Comment by lerno** [comment]
I've updated the docs, but there might be other issues. The current rules are that `@` is required in the name if the macro uses `&` or `#` parameters. Otherwise it's optional. Note that this also means that invocation and definition names now match. Please report any other problems in the docs with this.
